<?php
declare(strict_types = 1);
namespace PHP_Final_Project\Controllers;

use PHP_Final_Project\Frameworks\DIContainer;
use PHP_Final_Project\Models\NewPageModel;

class InitialPageController extends NewPageModel
{
    public function __construct(protected DIContainer $container)
    {
    }

    public function getNewPage()
    {
        parent::getNewPage(); // TODO: Change the autogenerated stub

        require __DIR__ . "./../../views/biblioteka.php";
    }
}